### ISSUE TITLE
CE-RO-V1 report is not generated

### ISSUE THREAD

**Issue by dinukadesilva** [ECLK/results-tabulation#505]
```
WHERE %(param_1)s = `templateRowColumn`.`templateRowId`
2020-03-07 13:36:20,134 INFO sqlalchemy.engine.base.Engine {'param_1': 102}
Traceback (most recent call last):
  File "/Users/lsf/Documents/lsf/repo/results-tabulation-api/rest/results-tabulation-api/venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/lsf/Documents/lsf/repo/results-tabulation-api/rest/results-tabulation-api/venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/lsf/Documents/lsf/repo/results-tabulation-api/rest/results-tabulation-api/venv/lib/python3.7/site-packages/connexion/decorators/decorator.py", line 48, in wrapper
    response = function(request)
  File "/Users/lsf/Documents/lsf/repo/results-tabulation-api/rest/results-tabulation-api/venv/lib/python3.7/site-packages/connexion/decorators/uri_parsing.py", line 143, in wrapper
    response = function(request)
  File "/Users/lsf/Documents/lsf/repo/results-tabulation-api/rest/results-tabulation-api/venv/lib/python3.7/site-packages/connexion/decorators/validation.py", line 172, in wrapper
    response = function(request)
  File "/Users/lsf/Documents/lsf/repo/results-tabulation-api/rest/results-tabulation-api/venv/lib/python3.7/site-packages/connexion/decorators/validation.py", line 347, in wrapper
    return function(request)
  File "/Users/lsf/Documents/lsf/repo/results-tabulation-api/rest/results-tabulation-api/venv/lib/python3.7/site-packages/connexion/decorators/parameter.py", line 126, in wrapper
    return function(**kwargs)
  File "</Users/lsf/Documents/lsf/repo/results-tabulation-api/rest/results-tabulation-api/venv/lib/python3.7/site-packages/decorator.py:decorator-gen-25>", line 2, in create
  File "</Users/lsf/Documents/lsf/repo/results-tabulation-api/rest/results-tabulation-api/venv/lib/python3.7/site-packages/decorator.py:decorator-gen-2>", line 2, in authorize
  File "/Users/lsf/Documents/lsf/repo/results-tabulation-api/rest/results-tabulation-api/auth/__init__.py", line 181, in authenticate
    return func(*args, **kwargs)
  File "/Users/lsf/Documents/lsf/repo/results-tabulation-api/rest/results-tabulation-api/auth/__init__.py", line 354, in authorize
    return func(*args, **kwargs)
  File "/Users/lsf/Documents/lsf/repo/results-tabulation-api/rest/results-tabulation-api/api/TallySheetVersionApi/__init__.py", line 108, in create
    content=request_body.get("content")
  File "/Users/lsf/Documents/lsf/repo/results-tabulation-api/rest/results-tabulation-api/orm/entities/Submission/TallySheet/__init__.py", line 628, in create_latest_version
    tallySheet, tallySheetVersion = create_version(tallySheetId, content=content)
  File "/Users/lsf/Documents/lsf/repo/results-tabulation-api/rest/results-tabulation-api/orm/entities/Submission/TallySheet/__init__.py", line 622, in create_version
    tallySheetVersion = tally_sheet.create_version(content=content)
  File "/Users/lsf/Documents/lsf/repo/results-tabulation-api/rest/results-tabulation-api/orm/entities/Submission/TallySheet/__init__.py", line 307, in create_version
    self.create_tally_sheet_version_rows(tally_sheet_version=tally_sheet_version, content=content, post_save=False)
  File "/Users/lsf/Documents/lsf/repo/results-tabulation-api/rest/results-tabulation-api/orm/entities/Submission/TallySheet/__init__.py", line 424, in create_tally_sheet_version_rows
    column_name_map[meta_data_key] == meta_data_map[meta_data_key]
KeyError: 'partyId'
```

**Comment by dinukadesilva** [comment]
This is a bug created from the fix done for https://github.com/ECLK/results-tabulation-api/issues/502
